GET http://localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inlhc2giLCJ1c2VySWQiOiI2ODkyMzljYTc4YmY0ZDllOTczMjJiYTciLCJpYXQiOjE3NTQ1MzI3NTksImV4cCI6MTc1NDUzMzY1OX0.t7Ao6-5m2lYECu0uQcxlxRxb9Npb02kGReOwloVKo8E

###
POST http://localhost:5000/api/v1/register
Content-Type: application/json

{
  "name": "yash",
  "email": "example1@gmail.com",
  "password": "app"
}

###
POST http://localhost:5000/api/v1/login
Content-Type: application/json

{
  "email": "example9@gmail.com",
  "password": "app"
}

###
GET http://localhost:5000/api/v1/refreshToken
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inlhc2giLCJ1c2VySWQiOiI2ODkyMzljYTc4YmY0ZDllOTczMjJiYTciLCJpYXQiOjE3NTQ0NTgwMDJ9.xIKd_R6xCFtlD9WDcnhO0BIf18Llp5NTqqu8CA4zK9c; Max-Age=604800; Path=/; Expires=Wed, 13 Aug 2025 05:26:42 GMT; HttpOnly; Secure; SameSite=Strict